replace main config with .circleci/test-deploy.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,36 +1,234 @@
 version: 2.1
-setup: true
 orbs:
+  android: circleci/android@dev:<<pipeline.git.revision>>
   orb-tools: circleci/orb-tools@11.1
-  shellcheck: circleci/shellcheck@3.1
 
 filters: &filters
   tags:
     only: /.*/
 
+prod-deploy-requires: &prod-deploy-requires
+  [
+    orb-tools/pack,
+    ui-tests-system-images;android-25;default;x86,
+    ui-tests-system-images;android-29;default;x86,
+    ui-tests-system-images;android-29;google_apis;x86_64,
+    test-emulator-commands,
+    test-start-emulator-and-run-tests,
+    test-java-version
+  ]
+
+jobs:
+  test-java-version:
+    parameters:
+      executor:
+        type: executor
+        description: |
+          Which Android image/executor to use. Choose between 'android-docker'
+          and 'android-machine'.
+      java-version:
+        type: integer
+        description: |
+          Version to use in the change-java-version job
+    executor: <<parameters.executor>>
+    steps:
+      - checkout
+      - android/change-java-version:
+          java-version: << parameters.java-version >>
+      - run:
+          command: |
+            JAVA_VER="$( java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1 )"
+            JAVAC_VER="$( javac -version 2>&1 | head -1 | cut -f 2- -d ' ' | sed '/^1\./s///' | cut -d'.' -f1 )"
+            if [ "$JAVA_VER" -ne <<parameters.java-version>> ] || [ "$JAVAC_VER" -ne <<parameters.java-version>> ]; then
+              echo "Job failed because either the java version or javac version was not changed."
+              exit 1
+            fi
+          name: check for correctness
+  
+  test-ndk-install:
+    parameters:
+      executor:
+        type: executor
+        description: |
+          Which Android image/executor to use. Choose between 'android-docker'
+          and 'android-machine'.
+      ndk:
+        type: string
+        description: ndk version to install
+    executor: << parameters.executor >>
+    steps:
+      - checkout
+      - android/install-ndk:
+          version: << parameters.ndk >>
+
+  test-emulator-commands:
+    parameters:
+      system-image:
+        type: string
+      tag:
+        type: string
+        description: "Android machine image tag to use."
+    executor:
+      name: android/android-machine
+      tag: << parameters.tag >>
+    steps:
+      - checkout
+      - run:
+          name: Clone project
+          command: |
+            git clone https://github.com/android/compose-samples
+            cd compose-samples
+            # pin the revision for consistency
+            git checkout f1e930dbe6f209dde9ceb5d3419bbf314aabcb58
+      - android/create-avd:
+          avd-name: test1
+          system-image: <<parameters.system-image>>
+          install: true
+      - android/start-emulator:
+          avd-name: test1
+          run-logcat: true
+          memory: 3072
+          restore-gradle-cache-prefix: v1-multiple
+          post-emulator-launch-assemble-command: "cd compose-samples/Owl && ./gradlew assembleDebugAndroidTest && cd ../Jetsnack && ./gradlew assembleDebugAndroidTest"
+      - android/run-tests:
+          working-directory: ./compose-samples/Owl
+      - android/run-tests:
+          working-directory: ./compose-samples/Jetsnack
+      - android/save-gradle-cache:
+          cache-prefix: v1-multiple
+      - android/kill-emulators
+      - run: sdkmanager "system-images;android-28;default;x86"
+      - android/create-avd:
+          avd-name: test2
+          system-image: system-images;android-28;default;x86
+          install: false
+      - android/start-emulator:
+          avd-name: test2
+          # we expect the no-window parameter to be overriden by override-args
+          no-window: true
+          override-args: "-delay-adb -verbose -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
+          wait-for-emulator: true
+          restore-gradle-cache-post-emulator-launch: false
+          post-emulator-launch-assemble-command: ""
+          disable-animations: false
+          pre-emulator-wait-steps:
+            - run:
+                name: Dummy pre-emulator-wait-steps
+                command: |
+                  echo "Test"
+          post-emulator-wait-steps:
+            - run:
+                name: Dummy post-emulator-wait-steps
+                command: |
+                  echo "Test"
+      - android/kill-emulators
+
+  test-start-emulator-and-run-tests:
+    parameters:
+      tag:
+        type: string
+        description: "Android machine image tag to use."
+    executor:
+      name: android/android-machine
+      tag: << parameters.tag >>
+      resource-class: xlarge
+    steps:
+      - checkout
+      - android/start-emulator-and-run-tests:
+          pre-emulator-wait-steps:
+            - run:
+                name: Clone project
+                command: |
+                    git clone https://github.com/android/compose-samples
+                    cd compose-samples
+                    # pin the revision for consistency
+                    git checkout f1e930dbe6f209dde9ceb5d3419bbf314aabcb58
+            - android/restore-build-cache
+            - run: cd compose-samples/Jetchat && ./gradlew assembleDebugAndroidTest
+          post-emulator-launch-assemble-command: ""
+          run-tests-working-directory: ./compose-samples/Jetchat
+          post-run-tests-steps:
+            - android/save-build-cache  
+
 workflows:
-  lint-pack:
+  test-deploy:
     jobs:
-      - orb-tools/lint:
+      - test-java-version:
+          name: "Test OpenJDK version change"
+          executor:
+            name: android/android-docker
+            tag: "2021.10.1"
+          matrix:
+            parameters:
+              java-version:
+                - 8
+                - 11
+                - 13
+          filters: *filters
+      - test-ndk-install:
+          name: "Test NDK Install on Android Docker"
+          matrix:
+            parameters:
+              executor:
+                - name: android/android-docker
+                  tag: "2021.10.1"
+                - name: android/android-docker
+                  tag: "2021.09.1"
+              ndk:
+                - "23.0.7599858"
+                - "21.4.7075529"
+                - "19.2.5345600"
+          filters: *filters
+      - test-ndk-install:
+          name: "Test NDK Install on Android Machine"
+          executor:
+            name: android/android-machine
+            tag: "2021.10.1"
+          matrix:
+            parameters:
+              ndk:
+                - "23.0.7599858"
+                - "21.4.7075529"
+                - "19.2.5345600"
+          filters: *filters
+      - android/run-ui-tests:
+          name: "ui-tests-<<matrix.system-image>>"
+          executor:
+            name: android/android-machine
+            tag: "202102-01"
+          checkout: false
+          pre-steps:
+            - run:
+                name: Setup project
+                command: |
+                  git clone https://github.com/android/compose-samples
+                  cd compose-samples
+                  # pin the revision for consistency
+                  git checkout f1e930dbe6f209dde9ceb5d3419bbf314aabcb58
+                  cd ..
+                  cp -r compose-samples/Jetchat/* .
+                  rm -rf compose-samples
+          matrix:
+            parameters:
+              system-image: ["system-images;android-29;default;x86", "system-images;android-29;google_apis;x86_64", "system-images;android-25;default;x86"]
+          filters: *filters
+      - test-emulator-commands:
+          system-image: "system-images;android-29;default;x86"
+          tag: "202102-01"
+          filters: *filters
+      - test-start-emulator-and-run-tests:
+          tag: "202102-01"
           filters: *filters
       - orb-tools/pack:
-          filters: *filters
-      - orb-tools/review:
-          filters: *filters
-      - shellcheck/check:
-          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
           filters: *filters
       - orb-tools/publish:
           orb-name: circleci/android
           vcs-type: << pipeline.project.type >>
-          requires:
-            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
-          # Use a context to hold your publishing token.
+          pub-type: production
+          requires: *prod-deploy-requires
           context: orb-publishing
-          filters: *filters
-      # Triggers the next workflow in the Orb Development Kit.
-      - orb-tools/continue:
-          pipeline-number: << pipeline.number >>
-          vcs-type: << pipeline.project.type >>
-          requires: [orb-tools/publish]
-          filters: *filters
+          filters:
+            branches:
+              ignore: /.*/
+            tags:
+              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
